# Generated by Django 5.2.3 on 2025-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.TextField(blank=True, help_text='Enter the answer for the question.', verbose_name='Answer'),
        ),
    ]
