# Generated by Django 5.2.3 on 2025-07-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('genre__name',)},
        ),
        migrations.AlterModelOptions(
            name='quizroom',
            options={'ordering': ('name', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('room__name', '-count')},
        ),
    ]
