# Generated by Django 5.2.3 on 2025-07-13 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_genre_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('room__name', '-index')},
        ),
        migrations.RemoveField(
            model_name='score',
            name='count',
        ),
        migrations.RemoveField(
            model_name='score',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='score',
            name='scores',
        ),
        migrations.AddField(
            model_name='score',
            name='detail',
            field=models.JSONField(blank=True, default=dict, help_text='Detail score of each member.', verbose_name='Detail score'),
        ),
        migrations.AddField(
            model_name='score',
            name='index',
            field=models.PositiveIntegerField(default=1, help_text='The n-th question', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='score',
            name='sequence',
            field=models.JSONField(blank=True, default=dict, help_text='Sequence of questions', verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='score',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='quiz.quizroom', verbose_name='Room'),
        ),
    ]
