# Generated by Django 5.2.3 on 2025-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_score_options_remove_score_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='name',
            field=models.CharField(help_text='Required. 128 characters or fewer.', max_length=128, verbose_name='Quiz room name'),
        ),
        migrations.AlterField(
            model_name='score',
            name='status',
            field=models.IntegerField(choices=[(1, 'Start'), (2, 'Waiting'), (3, 'Sent question'), (4, 'Answering'), (5, 'Received answers'), (6, 'Judging'), (7, 'End')], default=1, verbose_name='Status'),
        ),
    ]
