# Generated by Django 5.2.5 on 2025-09-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizroom_name_alter_score_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='use_typewriter_effect',
            field=models.BooleanField(default=False, help_text='Describes whether typewriter effect is used or not.', verbose_name='Use typewriter effect'),
        ),
    ]
