# Generated by Django 5.2.3 on 2025-06-22 06:27

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualgroup',
            options={'ordering': ('-created_at', 'name')},
        ),
        migrations.AddField(
            model_name='individualgroup',
            name='created_at',
            field=models.DateTimeField(default=utils.models.get_current_time, verbose_name='Created time'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=utils.models.get_current_time, verbose_name='Created time'),
        ),
    ]
