# Generated by Django 5.2.3 on 2025-06-22 07:10

import account.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_individualgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to=settings.AUTH_USER_MODEL, verbose_name='My friends'),
        ),
    ]
