# Generated by Django 5.2.3 on 2025-06-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualgroup',
            name='name',
            field=models.CharField(help_text='Required. 128 characters or fewer.', max_length=128, verbose_name='Group name'),
        ),
    ]
