# Generated by Django 5.2.5 on 2025-08-13 09:21

import django.db.models.deletion
import utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Required. 255 characters or fewer.', max_length=255, verbose_name='Passkey name')),
                ('is_enabled', models.BooleanField(default=True, help_text='Describes whether the passkey is enabled or not.', verbose_name='Passkey status')),
                ('platform', models.CharField(default='', help_text='Optional. 255 characters or fewer.', max_length=255, verbose_name='Platform')),
                ('created_at', models.DateTimeField(default=utils.models.get_current_time, verbose_name='Added time')),
                ('last_used', models.DateTimeField(default=None, null=True, verbose_name='Last used time')),
                ('credential_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Credential ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('name', '-last_used'),
            },
        ),
    ]
