# Generated by Django 5.2.5 on 2025-08-13 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasskey',
            name='credential_id',
            field=models.CharField(default=datetime.datetime(2025, 8, 13, 16, 35, 5, 674271, tzinfo=datetime.timezone.utc), max_length=255, unique=True, verbose_name='Credential ID'),
            preserve_default=False,
        ),
    ]
