# Generated by Django 5.2.5 on 2025-08-20 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passkey', '0002_alter_userpasskey_credential_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasskey',
            name='credential_id',
            field=models.CharField(max_length=255, verbose_name='Credential ID'),
        ),
        migrations.AddConstraint(
            model_name='userpasskey',
            constraint=models.UniqueConstraint(fields=('user', 'credential_id'), name='passkey_unique_user_credential'),
        ),
    ]
